name: flutter_colortheme_creator
description: "A new Flutter package project."
version: 0.0.3
homepage:
publish_to: none # without this line, it's not possible to use git-repos as dependencies.

environment:
  # sdk: ^3.10.7
  # flutter: ">=1.17.0"
  sdk: '^3.10.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  material_color_utilities: ^0.11.1
  # flutter_riverpod: ^3.2.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  riverpod: ^3.1.0
  riverpod_lint: ^3.1.0
  custom_lint: ^0.8.1


  # Regul채re Dependency (f체r Produktion)
  gui_creation_helper: 
  ### !!!!!!!!!!!! ATTENTION !!!!!!!!!!!! OVERRIDDEN IN DEPENDENCY OVERRIDES !!! (see directly below)
    git:
      url: https://github.com/qwizDev/flutter_gui_creation_helper.git
      # ref: someBranchName or someTagName
      ref: v0.0.2
  

dependency_overrides:
  
  # Lokale Version f체r Entwicklung (체berschreibt die git-Dependency)
  gui_creation_helper:
    path: /home/xy/prog/projekte/00_ownPackages/flutter/003-GuiCreationHelper/gui_creation_helper/
    # git:
      # url: https://github.com/qwizDev/flutter_gui_creation_helper.git
      # someBranchName or someTagName
      # ref: v0.0.2
      # ref: makePackageWorkThenCreateNewTag



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0+1
  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
